### ISSUE TITLE
nf version and nf-core tooling

### ISSUE THREAD

**Issue by DininduSenanayake** [GenomicsAotearoa/Nextflow_Workshop#1]
@christopher-hakkaart Opening an issue thread to address the following ( mainly to avoid me forgetting :) )   . I will address this shortly 

>The following code will print `22.10.3` regardless of the version I specify using an environmental variable.
```
# Load modules
module load Nextflow/22.10.3

# Check version - should print version 22.10.7
NXF_VER=22.10.7 nextflow info
```

>I suspect it’s to do with using the module but I’m unfamiliar with the system and don’t know if there is a way to change this.
A workaround is to install nextflow manually and add it to my path but I don’t want to teach people bad habits if there is a better way.
Similarly, the nf-core tooling isn’t available as a module and will need to be installed.

**Comment by DininduSenanayake** [comment]
@christopher-hakkaart This is a bit strange. I have added a new module **Nextflow/22.10.7**  to what's the output

* All is well with respect to `nextflow -v`
```bash
$ module load Nextflow/22.10.7

$ nextflow -v
nextflow version 22.10.7.5854
```
* However, `$NXF_VER` is still not showing the correct version

```
$ module load Nextflow/22.10.7

$ echo $NXF_VER 
22.10.3
```
It is the same for all other Nextflow modules before 23.04.1 .i.e. `nextflow -v` shows the correct version but `$NXF_VER` shows `22.10.3`

Then to make things a bit more complicated, `Nextflow/23.04.1` shows `22.10.7.5854` for `nextflow -v` and `$NXF_VER `22.10.3` 

```
$ module load Nextflow/23.04.1  

$ nextflow -v 
nextflow version 22.10.7.5854

$ echo $NXF_VER 
22.10.3
```

* * * 

All the modules are built with -all`  Binaries pulled from https://github.com/nextflow-io/nextflow/releases. So, this is a mystery :thinking:

**Comment by DininduSenanayake** [comment]
Ah..Okay, at least I have figured out why it was printing for me `22.10.3` as I have had a cached variable.  That solves part of the mystery. I will clean this up

**Comment by christopher-hakkaart** [comment]
Thanks so much!

I'm not as worried about the version number specifically. Pinning the version is a trick we normally show during the training, but it's not critical to the workshop.

The real issue will arise when we try and set a central repo for singularity images, e.g., `export NXF_SINGULARITY_CACHEDIR=</home/training/singularity_cache>`.

It will set a folder by default, but if we want to save the overhead of everyone downloading images it would be good to include this.

**Comment by jguhlin** [comment]
It looks like the Nextflow -all binaries do not support NXF_VER.  Good call on the cachedir.

**Comment by christopher-hakkaart** [comment]
Hi both - any recommendations for how to navigate this?

I've been stretched a little thin on time so I haven't looked into it.

How bad is it for everyone to install and add it to their path rather than use modules?

**Comment by DininduSenanayake** [comment]
@christopher-hakkaart Sorry for the late reply. I am on this now

It's perfectly fine for everyone to install and add to their paths rather than use modules. On the other hand, if we want to save few minutes here and there, modules will come in handy . We can always provide instructions on how to setup their own environment for other machines,etc. ( Took a similar approach with our snakemake workshop where we use https://nesi.github.io/snakemake_workshop/workshop_material/02_setup/ for the workshop day but added a [supplementary](https://nesi.github.io/snakemake_workshop/workshop_material/supplementary/99_appendix_setup_on_your_machine/) for local setup if needed)

All of the workshop attendees will have one common project under the code `nesi02659` which has a scratch space (Full path is `/nesi/nobackup/nesi02659`) . This can be used for caching  How about we provide a init.sh script for everyone which has all of the module load, CACHEDIR setups ,etc. For an example, take a look at **Example 2** on this page https://nesi.github.io/20230503-pfr-nfandarray/1_nf/. A modified version of it fit the expected file paths 

```
module purge
module load Singularity       
module load Nextflow/22.10.7

#Singularity and Nextflow variables
export SINGULARITY_TMPDIR=/nesi/nobackup/nesi02659/nextflow-workshop
export SINGULARITY_CACHEDIR=$SINGULARITY_TMPDIR

#Following is a NeSI specific instruction 
setfacl -b "$SINGULARITY_TMPDIR"

export NXF_SINGULARITY_CACHEDIR=$SINGULARITY_CACHEDIR
```

**Comment by christopher-hakkaart** [comment]
No worries @DininduSenanayake 

Nice idea! The scripts would give get us over the line but I'm leaning toward having everyone install it and add it to their paths.

It will take a little bit longer but means full functionality is retained and I can pull a couple of stunts where I show how you can add env variables to your execution command and execute dsl1 pipelines. Not overly important but some users might switch versions for older nf-core pipelines.

I've just pushed everything I have locally to the `dev_chris` branch for visibility.
