### ISSUE TITLE
"Cannot read project manifest -- Cause: API rate limit exceeded " - Appears to be random

### ISSUE THREAD

**Issue by DininduSenanayake** [GenomicsAotearoa/Nextflow_Workshop#7]
I was getting blocked by GH API rates for about 10 minutes as I was attempting to launch demo run

```bash
$ nextflow run christopher-hakkaart/nf-core-demo -profile test,singularity -r main
N E X T F L O W  ~  version 23.04.0
Pulling christopher-hakkaart/nf-core-demo ...
WARN: Cannot read project manifest -- Cause: API rate limit exceeded -- Provide your GitHub user name and password to get a higher rate limit
API rate limit exceeded -- Provide your GitHub user name and password to get a higher rate limit
```
* * * 

It appears to be random though. .i.e. It is working now without any changes . 

```bash
$ nextflow run christopher-hakkaart/nf-core-demo -profile test,singularity -r main
N E X T F L O W  ~  version 23.04.0
Pulling christopher-hakkaart/nf-core-demo ...
 downloaded from https://github.com/christopher-hakkaart/nf-core-demo.git
Launching `https://github.com/christopher-hakkaart/nf-core-demo` [loving_easley] DSL2 - revision: 7b5c17e325 [main]


------------------------------------------------------
                                        ,--./,-.
        ___     __   __   __   ___     /,-._.--~'
  |\ | |__  __ /  ` /  \ |__) |__         }  {
  | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                        `._,...
```

**Comment by DininduSenanayake** [comment]
I have ran this again at multiple time points and the error can not be reproduced. I am ore worried about these random failures than the ones which are consistent . 😟

**Comment by christopher-hakkaart** [comment]
Argh - that's a new error for me.

Without everyone signing into GitHub we might need to run this risk.

One quick solution could be to stash an assets folder with all of the pipelines in the shared folder and if anyone gets into trouble give them the code to use it instead: `export NXF_ASSETS=<path/to/folder>`

**Comment by DininduSenanayake** [comment]
Thanks @christopher-hakkaart Will do for sure. I will pull and store them in the shared space 😊

**Comment by DininduSenanayake** [comment]
@christopher-hakkaart I have created an assets directory in `/nesi/project/nesi02659/nextflow-workshop/assets` which has 

Therefore, `export NXF_ASSETS=/nesi/project/nesi02659/nextflow-workshop/assets` 

```bash
├── christopher-hakkaart
│   └── nf-core-demo
├── nextflow-io
│   └── hello
├── nf-core
│   └── sarek
├── null
│   └── pipeline_info
├── results
│   ├── fastqc
│   ├── multiqc
│   └── pipeline_info
└── work
    ├── 0c
    ............
````

**Comment by DininduSenanayake** [comment]
Regarding the Github API rate limit error, easiest way to deal with this when we are not running a workshop on Gitpod or so is to add the following content to  `$HOME/.nextflow/scm` configuration file.  `password = 'your-personal-access-token'` where the token is `gh_token` ( either we provide one token for all and give it to them on workshop day and delete it immediately after the workshop OR ask them to bring their own tokens)


```bash
providers {
    github {
        user = 'your-user-name'
        password = 'your-personal-access-token'
    }
}
```
