### ISSUE TITLE
custom configuration errors

### ISSUE THREAD

**Issue by wigge206** [GenomicsAotearoa/Nextflow_Workshop#8]
@christopher-hakkaart when I make .json files or config files with process, I get errors about missing required parameters. 

The current code causing issues:
```
nextflow run christopher-hakkaart/nf-core-demo -r main -params-file my_custom_params.json
nextflow run christopher-hakkaart/nf-core-demo -r main -resume -c custom.config
```

Adding `-profile test,singularity` allows the code to work as expected. Is this the best solution?
Also it would be worth adding `--out-dir my_results` to the three examples of changing parameters as its not default and your using that path to inspect files.

**Comment by christopher-hakkaart** [comment]
Thanks both. Have corrected 👍
