### ISSUE TITLE
Sarek memory errors

### ISSUE THREAD

**Issue by wigge206** [GenomicsAotearoa/Nextflow_Workshop#9]
The `NFCORE_SAREK:SAREK:PREPARE_INTERVALS:GATK4_INTERVALLISTTOBED (genome)` step require 12 GB memory. 

@christopher-hakkaart any solutions other than set more memory aside? 
@DininduSenanayake would >12 GB be excessive? Would only need to do this for the second day.

**Comment by DininduSenanayake** [comment]
This seems to switching between memory and CPU limit. 🤔 

 My process is getting terminated due to `CPUs -- req: 6; avail: 4`

```bash
WARN: There's no process matching config selector: NFCORE_SAREK:SAREK:CRAM_QC_NO_MD:SAMTOOLS_STATS -- Did you mean: NFCORE_SAREK:SAREK:CRAM_QC_RECAL:SAMTOOLS_STATS?
ERROR ~ Error executing process > 'NFCORE_SAREK:SAREK:PREPARE_GENOME:GATK4_CREATESEQUENCEDICTIONARY (genome.fasta)'

Caused by:
  Process requirement exceeds available CPUs -- req: 6; avail: 4
```

**Comment by christopher-hakkaart** [comment]
Thanks @wigge206 

I've added in `--max_cpu` and `--max_memory` to control the requests and stop the errors. I'll verbally describe these in more detail in the workshop and why they are required.

There are a few warnings I can't do much about without moving to a different version of the pipeline. I'll explain these as I go during the workshop as they aren't anything to worry about.
